### ISSUE TITLE
Bug/typo on adding footer

### ISSUE THREAD

**Issue by GastonZalba** [KaneCohen/modal-vanilla#25]
There is a typo in this [line](https://github.com/KaneCohen/modal-vanilla/blob/f6bd690fdeb80051de462b9523bd5e8b4a433fe2/lib/modal.js#L364) that prevents the footer from being constructed if it is added as a DOM element. It says `html.footer.ineerHTML` instead of `html.footer.innerHTML`.

On the other hand, wouldn't it be more useful if instead of using `innerHTML` and `outerHTML` you use `append`?. This would preserve the original DOM element and the existing listeners.

The final fix for the line could be `html.footer.append(o.footer)`. I can make a PR with this fix if it is useful.

Thanks

**Comment by KaneCohen** [comment]
Hi. Thanks for spotting the typo. Should be fixed in `v0.13.0` (already published)

About using `append()` - this can work, but there's an issue in the way element is assigned to Modal when doing `append()` or `appendChild()`. When running that function original element is removed and instead added to the Modal instance footer property.

Which means that if you want to instantiate 2 modals with the same footer - that will lead to issues where second instance won't actually have specified footer because it was already removed from original place in DOM.

There's also matter of events - I've never really had intentions for template elements to be anything more than template elements. If you do need to assign events - it's best done in custom event within the lifecycle of the modal instance like `shown`.
